[Settings]

# gif 图的名字
gif_path = normal.gif

# 提醒时显示的 gif 图名字
reminder_gif_path = touchhead.gif

# 每隔几分钟提醒一次
reminder_interval = 30

# 每次提醒持续的时长 (秒，有效范围 3-120)
# 提醒时长不可大于 reminder_interval
# 如果设置的时长超过限制，会自动调整为最大值
reminder_time = 60

# 共提醒多少次
reminder_count = 30

# 提醒内容
reminder_text = 该喝水了哦宝宝！记得保持水分充足哦~

# 提醒语颜色 (RGBA 格式)
reminder_text_color = (65, 112, 224, 1.0)

# 提醒截止时间 (24 小时制 HH:MM)
to_time = 23:00

# 天气城市代码 (0 为不启用，城市代码如 110000)
weather = 110000

# 天气 API key (高德开放平台 API key，用于获取天气信息，不可随意更改哦)
weather_key = 

# 提醒文字字体大小
drink_font_size = 12

# 天气文字字体大小
weather_font_size = 11

# 开机自启动 (0 为不启用，1 为启用)
auto_start = 0

# 会记住上次的位置
# 程序运行后在屏幕从左往右的距离
window_x = 720

# 程序运行后在屏幕从上往下的距离
window_y = 360
